services:
  user-db:
    networks:
      - app-network
    image: postgres:15
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: ["postgres", "-c", "port=${DB_PORT}"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    networks:
      - app-network
    build:
      context: .
      args:
        MAVEN_SKIP_TESTS: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5433/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SERVER_PORT=${SERVER_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - jwt.secret=${SECRET}
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - user-db

volumes:
  postgres_data:

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true